#!/bin/bash

function displayStartMessage() {
	echo "Usage: gitcloud <command> [options]"
	echo "$(cat ./.project/config/logo)"
	echo ""
	echo "Commands:"
	echo "   gitcloud start            Start the development environment"
	echo "   gitcloud stop             Stop the development environment"
	echo "   gitcloud install          Install necessary components of the development environment"
	echo "   gitcloud build            Build the development environment"
	echo "   gitcloud clean            Remove dangling docker images"
	echo ""
	echo "GitCloud v$(cat ./.project/version)"
}

function ensureConfig() {
    DIR="$HOME/.editor_config/"
    if [ -d "$DIR" ]; then
        mkdir ~/.editor_config &> /dev/null
        mkdir ~/.editor_config/extensions &> /dev/null
        touch ~/.editor_config/settings.json &> /dev/null
    fi
}

function envup() {
  local file=$([ -z "$1" ] && echo ".env" || echo ".env.$1")

  if [ -f "$file" ]; then
    set -a
    source $file
    set +a
  fi
}

function executeCommand() {
	if [ -f ./.project/scripts/"$1".sh ]; then
		bash .project/internal/spinner.sh ./.project/scripts/"$1".sh
	else
		displayStartMessage
	fi
}

ensureConfig && \
envup && \
executeCommand "$1"