services:
    vscode:
        container_name: ${PROJECT_NAME}_vscode
        build:
            context: "./vscode"
            dockerfile: Dockerfile.editor.complete
        volumes:
            - "~/.editor_config/extensions:/home/workspace/.openvscode-server/extensions"
            - "~/.editor_config/settings.json:/home/workspace/.openvscode-server/Machine/settings.json"
            - "~/.gitconfig:/home/workspace/.gitconfig"
            - "${PWD}:/home/workspace"
        ports:
            - ${EDITOR_PORT:-8080}:8443